<?php
require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Services\ReportDocumentGenerator;

$generator = new ReportDocumentGenerator();
$report = ['title' => 'Delivery Document', 'category' => 'delivery_document'];
$rows = [[
    'Tracking Number' => 'DPL-260809-ZRHOOXOW',
    'Document ID' => 'RPT-20260810-403063',
    'Reference' => 'REF-20260810094810-7KALYD',
    'Status' => 'Assigned',
    'Generated' => '10 August 2026 · 9:48 AM EAT',
    'Generated By' => 'System Administrator',
]];
$metadata = [
    'generated_by_name' => 'System Administrator',
    'reference_number' => 'REF-20260810094810-7KALYD',
    'report_id' => 'RPT-20260810-403063',
    'delivery_status' => 'Assigned',
    'generated_at' => '10 August 2026 · 9:48 AM EAT',
    'generated_by_line' => 'System Administrator',
    'created_at' => '09 August 2026 · 14:33 UTC',
    'document_version' => '1.0',
    'verification_status' => 'VERIFIED',
    'verification_id' => 'FEPFOZ5ZJLYESZVN',
    'verification_url' => 'https://portal.example.com/api/v1/reports/verify/FEPFOZ5ZJLYESZVN',
    'checksum' => 'sha256:deadbeef',
    'company_name' => 'DeliveryPortal',
];
$branding = [
    'platform_name' => 'DeliveryPortal',
    'company_registration_number' => 'REG-2026',
    'company_address' => '1 Security Ave, Enterprise City',
];
$response = $generator->buildPdf('sample.pdf', $rows, $report, $metadata, $branding, 'portrait', 'A4');
file_put_contents(__DIR__ . '/../sample_delivery_document.pdf', $response->getContent());
echo "Saved sample_delivery_document.pdf\n";
