<?php

namespace App\Services;

use Dompdf\Dompdf;
use Endroid\QrCode\Builder\Builder;
use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\Writer\PngWriter;
use Illuminate\Http\Response;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as SpreadsheetXlsxWriter;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\Writer\Word2007;
use Picqer\Barcode\BarcodeGeneratorPNG;

class ReportDocumentGenerator
{
    public function buildCsv(string $filename, array $rows, array $report, array $metadata, array $branding): Response
    {
        $stream = fopen('php://memory', 'w+');
        fwrite($stream, "\xEF\xBB\xBF");

        foreach ($this->buildMetadataLines($report, $metadata, $branding) as $metaRow) {
            fputcsv($stream, $metaRow);
        }

        fputcsv($stream, []);
        fputcsv($stream, ['Executive Summary']);
        fputcsv($stream, ['Total Records', (string) ($metadata['record_count'] ?? count($rows))]);
        fputcsv($stream, ['Generated By', $metadata['generated_by_line'] ?? ($metadata['generated_by_name'] ?? 'System')]);
        fputcsv($stream, ['Generated By Role', $metadata['generated_by_role'] ?? 'N/A']);
        fputcsv($stream, ['Report Scope', $report['category'] ?? 'N/A']);
        fputcsv($stream, ['Reporting Period', $metadata['reporting_period'] ?? 'All Available Records']);
        fputcsv($stream, ['Status', 'Official']);
        fputcsv($stream, ['Printed On', $metadata['printed_on'] ?? $metadata['generated_at'] ?? 'N/A']);
        fputcsv($stream, ['Printed By', $metadata['printed_by_user'] ?? 'System']);
        fputcsv($stream, ['Timezone', $metadata['printed_timezone'] ?? 'East Africa Time (EAT) – Africa/Addis_Ababa (UTC+03:00)']);
        fputcsv($stream, []);

        if (! empty($rows)) {
            $headers = array_keys($rows[0]);
            fputcsv($stream, $headers);
            foreach ($rows as $row) {
                fputcsv($stream, array_map(fn ($value) => $this->normalizeValue($value), $row));
            }
        } else {
            fputcsv($stream, ['No data available']);
        }

        rewind($stream);
        $content = stream_get_contents($stream);
        fclose($stream);

        return response($content, 200, [
            'Content-Type' => 'text/csv; charset=utf-8',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }

    public function buildXlsx(string $filename, array $rows, array $report, array $metadata, array $branding): Response
    {
        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setTitle($report['title'] . ' Report')
            ->setSubject($report['category'] ?? 'System Export')
            ->setCreator($metadata['generated_by_name'] ?? 'System')
            ->setCompany($branding['platform_name'] ?? 'Integration Delivery Portal')
            ->setDescription('System-generated report export with audit metadata and secure verification details.');

        $summarySheet = $spreadsheet->getActiveSheet();
        $summarySheet->setTitle('Report Summary');
        $summarySheet->mergeCells('A1:B1');
        $summarySheet->setCellValue('A1', strtoupper($report['title']));
        $summarySheet->getStyle('A1')->getFont()->setBold(true)->setSize(14)->getColor()->setRGB('0F172A');
        $summarySheet->getStyle('A1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('E0F2FE');

        $summarySheet->fromArray(['Field', 'Value'], null, 'A2');
        $summarySheet->fromArray($this->buildMetadataLines($report, $metadata, $branding), null, 'A3');
        $summarySheet->getStyle('A2:B2')->getFont()->setBold(true);
        $summarySheet->getStyle('A2:B2')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('1D4ED8');
        $summarySheet->getStyle('A2:B2')->getFont()->getColor()->setRGB('FFFFFF');
        $summarySheet->getStyle('A3:B' . ($summarySheet->getHighestRow()))->getAlignment()->setWrapText(true);
        $summarySheet->getColumnDimension('A')->setAutoSize(true);
        $summarySheet->getColumnDimension('B')->setWidth(72);
        $summarySheet->freezePane('A3');

        $dataSheet = $spreadsheet->createSheet();
        $dataSheet->setTitle('Details');
        $dataSheet->setAutoFilter('A1:Z1');

        if (! empty($rows)) {
            $headers = array_keys($rows[0]);
            $dataSheet->fromArray($headers, null, 'A1');
            $dataSheet->fromArray(array_map(fn ($row) => array_values($row), $rows), null, 'A2');

            $headerRange = 'A1:' . $dataSheet->getHighestColumn() . '1';
            $dataSheet->getStyle($headerRange)->getFont()->setBold(true);
            $dataSheet->getStyle($headerRange)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('E2E8F0');
            $dataSheet->setAutoFilter($headerRange);
            $dataSheet->freezePane('A2');

            foreach (range('A', $dataSheet->getHighestColumn()) as $column) {
                $dataSheet->getColumnDimension($column)->setAutoSize(true);
            }

            $this->applyConditionalFormatting($dataSheet, $rows);
        } else {
            $dataSheet->setCellValue('A1', 'No data available.');
        }

        $approvalSheet = $spreadsheet->createSheet();
        $approvalSheet->setTitle('Approval');
        $approvalSheet->setCellValue('A1', 'Authorized Export Approval');
        $approvalSheet->mergeCells('A1:D1');
        $approvalSheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
        $approvalSheet->fromArray([
            ['Prepared By'],
            ['Name:', '______________________________'],
            ['Position:', '______________________________'],
            ['Signature:', '______________________________'],
            ['Date:', '______________________________'],
            [],
            ['Reviewed By'],
            ['Name:', '______________________________'],
            ['Position:', '______________________________'],
            ['Signature:', '______________________________'],
            ['Date:', '______________________________'],
            [],
            ['Approved By'],
            ['Name:', '______________________________'],
            ['Position:', '______________________________'],
            ['Official Signature:', '______________________________'],
            ['Official Stamp / Seal:', '______________________________'],
            ['Approval Date:', '______________________________'],
            [],
            ['Printed By'],
            ['System User:', $metadata['printed_by_user'] ?? 'N/A'],
            ['Role:', $metadata['printed_by_role'] ?? 'N/A'],
            ['Department:', $metadata['printed_by_department'] ?? 'N/A'],
            ['Printed On:', $metadata['printed_on'] ?? 'N/A'],
            ['Timezone:', $metadata['printed_timezone'] ?? 'East Africa Time (EAT) – Africa/Addis_Ababa (UTC+03:00)'],
            ['Signature:', '______________________________'],
        ], null, 'A2');
        $approvalSheet->getStyle('A1:B1')->getFont()->setBold(true);
        $approvalSheet->getStyle('A2:B' . $approvalSheet->getHighestRow())->getAlignment()->setVertical('center');
        $approvalSheet->getColumnDimension('A')->setWidth(28);
        $approvalSheet->getColumnDimension('B')->setWidth(52);

        $spreadsheet->setActiveSheetIndex(0);

        $writer = new SpreadsheetXlsxWriter($spreadsheet);
        ob_start();
        $writer->save('php://output');
        $content = ob_get_clean();

        return response($content, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }

    public function buildDocx(string $filename, array $rows, array $report, array $metadata, array $branding): Response
    {
        $phpWord = new PhpWord();
        $section = $phpWord->addSection(['marginLeft' => 600, 'marginRight' => 600, 'marginTop' => 600, 'marginBottom' => 600]);

        $this->addDocxHeader($section, $report, $metadata, $branding);
        $section->addTextBreak(1);
        $this->addDocxExecutiveSummary($section, $report, $metadata, $rows);
        $section->addTextBreak(1);

        $table = $section->addTable(['borderSize' => 4, 'borderColor' => '1D4ED8', 'cellMargin' => 80, 'bgColor' => 'F8FAFC']);
        foreach ($this->buildMetadataLines($report, $metadata, $branding) as $line) {
            $table->addRow();
            $table->addCell(3200)->addText($line[0], ['bold' => true, 'color' => '0F172A']);
            $table->addCell(8600)->addText($line[1], ['color' => '334155']);
        }

        $section->addTextBreak(1);
        $detailsHeading = 'Export Details';

        $section->addText($detailsHeading, ['bold' => true, 'size' => 16, 'color' => '0F172A']);
        $section->addTextBreak(1);

        if (! empty($rows)) {
            if (count($rows) === 1 && in_array($report['category'] ?? '', ['delivery_document', 'delivery_form'], true)) {
                $row = $rows[0];
                $detailTable = $section->addTable(['borderSize' => 4, 'borderColor' => '94A3B8', 'cellMargin' => 80]);
                foreach ($row as $label => $value) {
                    $detailTable->addRow();
                    $detailTable->addCell(3200)->addText((string) $label, ['bold' => true, 'color' => '0F172A']);
                    $detailTable->addCell(8600)->addText($this->normalizeValue($value), ['color' => '334155']);
                }
            } else {
                $dataTable = $section->addTable(['borderSize' => 4, 'borderColor' => '94A3B8', 'cellMargin' => 80]);
                $dataTable->addRow();
                foreach (array_keys($rows[0]) as $header) {
                    $dataTable->addCell(2200)->addText((string) $header, ['bold' => true, 'color' => 'FFFFFF'], ['bgColor' => '1D4ED8']);
                }

                foreach ($rows as $row) {
                    $dataTable->addRow();
                    foreach (array_values($row) as $cell) {
                        $dataTable->addCell(2200)->addText($this->normalizeValue($cell), ['color' => '334155']);
                    }
                }
            }
        } else {
            $section->addText('No data available.', ['size' => 11, 'color' => '777777']);
        }

        $section->addTextBreak(1);
        $this->addDocxRevisionHistory($section, $metadata);
        $section->addTextBreak(1);
        $this->addDocxApprovalPanel($section, $metadata);
        $section->addTextBreak(1);
        $this->addDocxVerificationBlock($section, $metadata);

        $writer = new Word2007($phpWord);
        ob_start();
        $writer->save('php://output');
        $content = ob_get_clean();

        return response($content, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }

    public function buildPdf(string $filename, array $rows, array $report, array $metadata, array $branding, string $orientation = 'portrait', string $paperSize = 'A4'): Response
    {
        $qrPayload = $this->buildQrPayload($metadata);
        $qrDataUri = $this->buildQrCodeDataUri($qrPayload);
        $barcodeDataUri = $this->buildBarcodeDataUri($metadata['reference_number'] . '|' . ($metadata['verification_id'] ?? ''));

        $html = $this->buildPdfHtml($report, $rows, $metadata, $branding, $qrDataUri, $barcodeDataUri);

        $dompdf = new Dompdf();
        // Enable inline PHP for page numbering (dompdf page_text)
        $dompdf->getOptions()->set('isPhpEnabled', true);
        $dompdf->loadHtml($html);
        $dompdf->setPaper($paperSize, $orientation);
        $dompdf->render();

        return response($dompdf->output(), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }

    private function buildMetadataLines(array $report, array $metadata, array $branding): array
    {
        $lines = [
            ['Report Title', $report['title'] ?? 'N/A'],
            ['Report Category', $report['category'] ?? 'N/A'],
            ['Report ID', $metadata['report_id'] ?? $metadata['reference_number'] ?? 'N/A'],
            ['Reference Number', $metadata['reference_number'] ?? 'N/A'],
        ];

        if (! empty($metadata['delivery_tracking_number'])) {
            $lines[] = ['Delivery Tracking Number', $metadata['delivery_tracking_number']];
        }

        if (! empty($metadata['delivery_status'])) {
            $lines[] = ['Delivery Status', $metadata['delivery_status']];
        }

        if (! empty($metadata['delivery_reference'])) {
            $lines[] = ['Delivery Reference', $metadata['delivery_reference']];
        }

        $lines = array_merge($lines, [
            ['Document Version', $metadata['document_version'] ?? '1.0'],
            ['Generated By', $metadata['generated_by_line'] ?? ($metadata['generated_by_name'] ?? 'System')],
            ['Generated By Role', $metadata['generated_by_role'] ?? 'N/A'],
            ['Company Name', $metadata['company_name'] ?? ($branding['platform_name'] ?? 'Logistics Integration Portal')],
            ['Company ID', $metadata['company_id'] ?? 'N/A'],
            ['Company Registration Number', $branding['company_registration_number'] ?? 'N/A'],
            ['Company Address', $branding['company_address'] ?? 'N/A'],
            ['Company Website', $branding['company_website'] ?? 'N/A'],
            ['Support Email', $branding['support_email'] ?? 'N/A'],
            ['Generation Date', $metadata['generated_at'] ?? now()->setTimezone('Africa/Addis_Ababa')->format('l, d F Y • g:i:s A') . ' EAT (UTC+03:00)'],
            ['Environment', $metadata['environment'] ?? 'Production'],
            ['Confidentiality', $metadata['confidentiality'] ?? 'Confidential'],
            ['Record Count', (string) ($metadata['record_count'] ?? 0)],
            ['Verification URL', $metadata['verification_url'] ?? 'N/A'],
            ['Digital Verification Code', $metadata['verification_id'] ?? 'N/A'],
            ['Security Hash', $metadata['checksum'] ?? 'N/A'],
        ]);

        return $lines;
    }

    private function addDocxHeader($section, array $report, array $metadata, array $branding): void
    {
        $documentTitle = $report['title'] ?? 'System Export Document';
        $documentSubtitle = $report['description'] ?? 'Verified system export record.';

        $company = $metadata['company_name'] ?? ($branding['platform_name'] ?? 'Integration Delivery Portal');
        $platformName = $branding['platform_name'] ?? 'Integration Delivery Portal';

        $section->addText($company, ['bold' => true, 'size' => 16, 'color' => '0F172A'], ['spaceAfter' => 0]);
        $section->addText($documentTitle, ['bold' => true, 'size' => 14, 'color' => '1D4ED8'], ['spaceAfter' => 0]);
        $section->addText($documentSubtitle, ['size' => 9, 'color' => '475569'], ['spaceAfter' => 0]);
        $section->addTextBreak(1);
        $section->addText('System export record', ['size' => 9, 'color' => '334155'], ['spaceAfter' => 0]);
        $section->addText('OFFICIAL COPY • CONFIDENTIAL', ['bold' => true, 'size' => 9, 'color' => '0F172A'], ['spaceAfter' => 0]);

        // Small, unobtrusive verification line (do not display localhost)
        if (! empty($metadata['verification_url'])) {
            $section->addText('Verification: ' . $metadata['verification_url'], ['size' => 8, 'color' => '475569'], ['spaceAfter' => 0]);
        }
    }

    private function addDocxExecutiveSummary($section, array $report, array $metadata, array $rows): void
    {
        // Compact document summary for delivery documents
        $section->addText('EXPORT SUMMARY', ['bold' => true, 'size' => 12, 'color' => '0F172A'], ['spaceAfter' => 0]);

        $reportTitle = $report['title'] ?? 'System Export Document';
        $reportCategory = $report['category'] ?? 'System Export';
        $status = $metadata['export_status'] ?? $metadata['delivery_status'] ?? 'N/A';
        $generated = $metadata['generated_at'] ?? now()->setTimezone('Africa/Addis_Ababa')->format('Y-m-d H:i:s') . ' EAT';
        $generatedBy = $metadata['generated_by_line'] ?? ($metadata['generated_by_name'] ?? 'System');

        $run = $section->addTextRun();
        $run->addText('Report Title', ['bold' => true, 'size' => 10, 'color' => '0F172A']);
        $run->addText(' ' . $reportTitle . '  ', ['size' => 10, 'color' => '334155']);
        $run->addText('Category', ['bold' => true, 'size' => 10, 'color' => '0F172A']);
        $run->addText(' ' . $reportCategory . '  ', ['size' => 10, 'color' => '334155']);
        $run->addText('Reference', ['bold' => true, 'size' => 10, 'color' => '0F172A']);
        $run->addText(' ' . ($metadata['reference_number'] ?? 'N/A') . '  ', ['size' => 10, 'color' => '334155']);
        $run->addText('Status', ['bold' => true, 'size' => 10, 'color' => '0F172A']);
        $run->addText(' ' . $status . '  ', ['size' => 10, 'color' => '334155']);
        $run->addText('Generated', ['bold' => true, 'size' => 10, 'color' => '0F172A']);
        $run->addText(' ' . $generated . '  ', ['size' => 10, 'color' => '334155']);
        $run->addText('Generated By', ['bold' => true, 'size' => 10, 'color' => '0F172A']);
        $run->addText(' ' . $generatedBy, ['size' => 10, 'color' => '334155']);
    }

    private function addDocxRevisionHistory($section, array $metadata): void
    {
        $section->addText('Revision History', ['bold' => true, 'size' => 14, 'color' => '0F172A']);
        $section->addText('Export Version: ' . ($metadata['document_version'] ?? '1.0'), ['size' => 10, 'color' => '334155']);
        $section->addText('Audit Event ID: ' . ($metadata['audit_event_id'] ?? 'N/A'), ['size' => 10, 'color' => '334155']);
        $section->addText('Generation Timestamp: ' . ($metadata['generated_at'] ?? now()->setTimezone('Africa/Addis_Ababa')->format('l, d F Y • g:i:s A') . ' EAT (UTC+03:00)'), ['size' => 10, 'color' => '334155']);
    }

    private function addDocxVerificationBlock($section, array $metadata): void
    {
        $section->addText('EXPORT VERIFICATION', ['bold' => true, 'size' => 12, 'color' => '0F172A']);
        $status = strtoupper($metadata['verification_status'] ?? 'VERIFIED');
        $section->addText('Status: ' . ($status === 'VERIFIED' ? '✓ VERIFIED' : $status), ['size' => 10, 'color' => '0F172A']);
        $section->addText('Verification Code: ' . ($metadata['verification_id'] ?? 'N/A'), ['size' => 10, 'color' => '334155']);
        $section->addText('Scan to verify this export through the system verification service.', ['italic' => true, 'size' => 9, 'color' => '475569']);
    }

    private function addDocxApprovalPanel($section, array $metadata): void
    {
        // Show at most one authorization block in DOCX: priority Approved -> Reviewed -> Prepared
        $section->addText('Executive Approval', ['bold' => true, 'size' => 14, 'color' => '0F172A']);
        $section->addTextBreak(1);

        // Always show a single Prepared By block for DOCX to match sample
        $auth = [
            'title' => 'Prepared By',
            'name' => $metadata['prepared_by_name'] ?? '______________________________',
            'position' => $metadata['prepared_by_position'] ?? '______________________________',
            'date' => $metadata['prepared_by_date'] ?? '______________________________',
        ];

        $table = $section->addTable(['borderSize' => 6, 'borderColor' => 'E6EEF8', 'cellMargin' => 80]);
        $table->addRow();
        $cell = $table->addCell(9600);
        $cell->addText($auth['title'], ['bold' => true, 'size' => 11, 'color' => '0F172A']);
        $cell->addTextBreak(1);
        $cell->addText('Name: ' . $auth['name'], ['size' => 10, 'color' => '334155']);
        $cell->addText('Position: ' . $auth['position'], ['size' => 10, 'color' => '334155']);
        $cell->addText('Date: ' . $auth['date'], ['size' => 10, 'color' => '334155']);
    }

    private function buildPdfHtml(array $report, array $rows, array $metadata, array $branding, string $qrDataUri, string $barcodeDataUri): string
    {
        $platformName = htmlspecialchars($branding['platform_name'] ?? 'Integration Delivery Portal', ENT_QUOTES, 'UTF-8');
        $companyName = htmlspecialchars($metadata['company_name'] ?? ($branding['platform_name'] ?? 'Integration Delivery Portal'), ENT_QUOTES, 'UTF-8');
        $documentType = htmlspecialchars(strtoupper(str_replace('_', ' ', $report['category'] ?? 'SYSTEM EXPORT')), ENT_QUOTES, 'UTF-8');
        $documentTitle = htmlspecialchars($report['title'] ?? 'Official Export Document', ENT_QUOTES, 'UTF-8');
        $referenceNumber = htmlspecialchars($metadata['reference_number'] ?? ($metadata['report_id'] ?? 'N/A'), ENT_QUOTES, 'UTF-8');
        $documentId = htmlspecialchars($metadata['report_id'] ?? $referenceNumber, ENT_QUOTES, 'UTF-8');
        $trackingNumber = htmlspecialchars($metadata['delivery_tracking_number'] ?? $metadata['tracking_number'] ?? $referenceNumber, ENT_QUOTES, 'UTF-8');
        $verificationId = htmlspecialchars($metadata['verification_id'] ?? 'N/A', ENT_QUOTES, 'UTF-8');
        $status = htmlspecialchars($metadata['export_status'] ?? $metadata['delivery_status'] ?? 'Verified', ENT_QUOTES, 'UTF-8');
        $generatedAt = htmlspecialchars($metadata['generated_at'] ?? now()->setTimezone('Africa/Addis_Ababa')->format('d F Y · g:i A') . ' EAT', ENT_QUOTES, 'UTF-8');
        $preparedName = htmlspecialchars($metadata['prepared_by_name'] ?? '________________', ENT_QUOTES, 'UTF-8');
        $preparedPosition = htmlspecialchars($metadata['prepared_by_position'] ?? '________________', ENT_QUOTES, 'UTF-8');
        $preparedDate = htmlspecialchars($metadata['prepared_by_date'] ?? '________________', ENT_QUOTES, 'UTF-8');
        $documentVersion = htmlspecialchars($metadata['document_version'] ?? '1.0', ENT_QUOTES, 'UTF-8');
        $recordCount = htmlspecialchars((string) ($metadata['record_count'] ?? count($rows)), ENT_QUOTES, 'UTF-8');

        $verificationUrl = htmlspecialchars($metadata['verification_url'] ?? 'N/A', ENT_QUOTES, 'UTF-8');

        $documentRowsHtml = '';
        foreach ([
            ['Document Type', $documentType],
            ['Document Title', $documentTitle],
            ['Document ID', $documentId],
            ['Tracking Number', $trackingNumber],
            ['Reference Number', $referenceNumber],
            ['Verification Code', $verificationId],
            ['Verification URL', $verificationUrl],
            ['Status', $status],
            ['Generated On', $generatedAt],
        ] as [$label, $value]) {
            $documentRowsHtml .= "<div class=\"detail-row\"><span class=\"detail-label\">{$label}</span><span class=\"detail-value\">{$value}</span></div>";
        }

        $contentRows = [];
        if (! empty($rows) && is_array($rows[0])) {
            foreach ($rows as $row) {
                if (! is_array($row)) {
                    continue;
                }
                foreach ($row as $label => $value) {
                    if ($value === null || $value === '') {
                        continue;
                    }
                    $contentRows[$label] = htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
                }
            }
        }

        if (empty($contentRows)) {
            $contentRows = [
                'Generated By' => htmlspecialchars($metadata['generated_by_line'] ?? ($metadata['generated_by_name'] ?? 'System'), ENT_QUOTES, 'UTF-8'),
                'Document Version' => $documentVersion,
                'Record Count' => $recordCount,
            ];
        }

        $contentHtml = '<div class="content-grid">';
        foreach ($contentRows as $label => $value) {
            $contentHtml .= "<div class=\"content-row\"><span class=\"content-label\">{$label}</span><span class=\"content-value\">{$value}</span></div>";
        }
        $contentHtml .= '</div>';

        $css = trim(<<<'CSS'
        * { box-sizing: border-box; }
        html, body { margin: 0; padding: 0; background: #f8fafc; color: #0f172a; font-family: Inter, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1.6; }
        .document { width: 210mm; min-height: 297mm; margin: 12px auto; padding: 24mm 22mm 18mm; background: #ffffff; position: relative; }
        .document-header { padding-bottom: 14px; margin-bottom: 26px; }
        .document-banner { display: grid; grid-template-columns: 1fr auto; gap: 18px; align-items: center; }
        .document-title { margin: 0; font-size: 32px; line-height: 1.05; font-weight: 900; letter-spacing: 0.18px; text-transform: uppercase; color: #0f172a; }
        .document-subtitle { margin: 10px 0 0; font-size: 11px; color: #475569; font-weight: 700; letter-spacing: 0.14em; text-transform: uppercase; }
        .document-seal { display: inline-flex; align-items: center; justify-content: center; width: 96px; height: 96px; border-radius: 50%; background: #eef2ff; color: #1d4ed8; font-size: 10px; font-weight: 800; text-align: center; padding: 8px; line-height: 1.2; }
        .document-labels { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 18px; }
        .label { display: inline-flex; align-items: center; justify-content: center; padding: 8px 14px; border-radius: 999px; font-size: 8px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.13em; background: #eef2ff; color: #1d4ed8; }
        .label.confidential { background: #fee2e2; color: #991b1b; }
        .section { margin-top: 30px; }
        .section-title { margin: 0 0 10px; font-size: 11px; font-weight: 800; letter-spacing: 0.18em; text-transform: uppercase; color: #0f172a; }
        .section-description { margin: 0 0 18px; color: #475569; font-size: 10px; line-height: 1.7; }
        .detail-card { background: #f8fafc; border-radius: 22px; padding: 22px; }
        .detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }
        .detail-row { display: grid; grid-template-columns: 180px 1fr; gap: 14px; padding: 10px 0; }
        .detail-row:not(:last-child) { border-bottom: 1px solid rgba(15, 23, 42, 0.08); }
        .detail-label { font-size: 9px; font-weight: 700; color: #334155; text-transform: uppercase; letter-spacing: 0.08em; }
        .detail-value { font-size: 10.2px; font-weight: 600; color: #111827; }
        .verification { display: grid; grid-template-columns: 1fr auto; gap: 20px; background: #ffffff; border-radius: 22px; padding: 24px; border: 1px solid #E2E8F0; }
        .verification-info { display: grid; gap: 14px; }
        .verification-row { display: flex; justify-content: space-between; gap: 16px; font-size: 10px; color: #0f172a; }
        .verification-label { font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.08em; }
        .verification-value { font-weight: 700; color: #0f172a; }
        .verification-status { display: inline-flex; align-items: center; gap: 8px; font-weight: 700; color: #166534; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; }
        .verification-note { margin: 0; color: #475569; font-size: 9px; line-height: 1.6; }
        .qr-container { width: 108px; height: 108px; border-radius: 22px; background: #f8fafc; display: flex; align-items: center; justify-content: center; border: 1px solid #E2E8F0; }
        .qr-container img { width: 90px; height: 90px; object-fit: contain; }
        .content-grid { display: grid; gap: 12px; }
        .content-row { display: flex; justify-content: space-between; gap: 14px; }
        .content-label { font-size: 9px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.12em; }
        .content-value { font-size: 11px; font-weight: 600; color: #0f172a; text-align: right; }
        .document-footer { margin-top: 28px; font-size: 9px; color: #475569; line-height: 1.7; text-align: center; }
        .document-footer strong { color: #0f172a; }
        @page { size: A4; margin: 0; }
        @media print { html, body { background: #ffffff; margin: 0; padding: 0; } .document { width: 210mm; min-height: 297mm; margin: 0; padding: 24mm 22mm 18mm; } .section, .verification, .detail-card { break-inside: avoid; page-break-inside: avoid; } }
CSS);

        $html = <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{$documentTitle}</title>
            <style>{$css}</style>
        </head>
        <body>

        <div class="document">
            <header class="document-header">
                <div class="document-banner">
                    <div>
                        <h1 class="document-title">{$documentTitle}</h1>
                        <p class="document-subtitle">{$documentType} · Official Export Record</p>
                    </div>
                    <div class="document-seal">OFFICIAL<br>COPY</div>
                </div>
                <div class="document-labels">
                    <span class="label">Issued by {$platformName}</span>
                    <span class="label">SYSTEM GENERATED</span>
                    <span class="label confidential">CONFIDENTIAL</span>
                </div>
            </header>

            <section class="section">
                <h2 class="section-title">Document details</h2>
                <p class="section-description">This official export is generated from the portal and is protected by digital verification metadata.</p>
                <div class="detail-card">
                    <div class="detail-grid">
                        {$documentRowsHtml}
                    </div>
                </div>
            </section>

            <section class="section">
                <h2 class="section-title">Statement details</h2>
                <div class="detail-card">
                    {$contentHtml}
                </div>
            </section>

            <section class="section">
                <h2 class="section-title">Verification summary</h2>
                <div class="verification">
                    <div class="verification-info">
                        <div class="verification-row"><span class="verification-label">Verification Code</span><span class="verification-value">{$verificationId}</span></div>
                        <div class="verification-row"><span class="verification-label">Document Status</span><span class="verification-status">{$status}</span></div>
                        <p class="verification-note">Scan the QR code to verify this export against the secure portal record and audit trail.</p>
                    </div>
                    <div class="qr-container"><img src="{$qrDataUri}" alt="Verification QR Code"></div>
                </div>
            </section>

            <section class="section">
                <h2 class="section-title">Authorized by</h2>
                <div class="detail-card">
                    <div class="detail-grid">
                        <div class="detail-row"><span class="detail-label">Prepared by</span><span class="detail-value">{$preparedName}</span></div>
                        <div class="detail-row"><span class="detail-label">Position</span><span class="detail-value">{$preparedPosition}</span></div>
                        <div class="detail-row"><span class="detail-label">Date</span><span class="detail-value">{$preparedDate}</span></div>
                    </div>
                </div>
            </section>

            <footer class="document-footer">
                <p><strong>OFFICIAL DIGITAL RECORD</strong></p>
                <p><strong>SYSTEM GENERATED</strong> · <strong>OFFICIAL COPY</strong> · <strong>CONFIDENTIAL</strong></p>
                <p>Issued by {$platformName}. Generated on {$generatedAt}. Verification token is embedded in the QR code and system audit metadata.</p>
            </footer>
        </div>

        <script type="text/php">
        if (isset(\$pdf)) {
            \$font = \$fontMetrics->get_font('Helvetica', 'normal');
            \$y = \$pdf->get_height() - 18;
            \$x = (\$pdf->get_width() / 2) - 50;
            \$text = 'Page ' . \$PAGE_NUM . ' of ' . \$PAGE_COUNT;
            \$pdf->page_text(\$x, \$y, \$text, \$font, 9, array(0.4,0.4,0.4));
        }
        </script>

        </body>
        </html>
HTML;

        return $html;
    }

    private function applyConditionalFormatting($sheet, array $rows): void
    {
        if (empty($rows)) {
            return;
        }

        $highestColumn = $sheet->getHighestColumn();
        $highestRow = $sheet->getHighestRow();
        $statusColumn = null;

        foreach (range('A', $highestColumn) as $column) {
            if (strtolower((string) $sheet->getCell($column . '1')->getValue()) === 'status') {
                $statusColumn = $column;
                break;
            }
        }

        if ($statusColumn !== null) {
            $sheet->getStyle("{$statusColumn}2:{$statusColumn}{$highestRow}")
                ->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setARGB('E0F2FE');
        }
    }

    private function buildQrPayload(array $metadata): string
    {
        return $metadata['verification_url'] ?? '';
    }

    private function buildPdfApprovalPanelHtml(array $metadata): string
    {
        $preparedBy = htmlspecialchars($metadata['printed_by_user'] ?? 'N/A', ENT_QUOTES, 'UTF-8');
        $role = htmlspecialchars($metadata['printed_by_role'] ?? 'N/A', ENT_QUOTES, 'UTF-8');
        $department = htmlspecialchars($metadata['printed_by_department'] ?? 'N/A', ENT_QUOTES, 'UTF-8');
        $printedOn = htmlspecialchars($metadata['printed_on'] ?? '', ENT_QUOTES, 'UTF-8');
        $timezone = htmlspecialchars($metadata['printed_timezone'] ?? 'East Africa Time (EAT) – Africa/Addis_Ababa (UTC+03:00)', ENT_QUOTES, 'UTF-8');

        $html = '<div style="display:grid;grid-template-columns:1fr 1fr;gap:22px;font-size:11px;color:#334155;line-height:1.6;">';
        $html .= $this->buildApprovalBlockHtml('Prepared By', ['Name:', '______________________________', 'Position:', '______________________________', 'Signature:', '______________________________', 'Date:', '______________________________']);
        $html .= $this->buildApprovalBlockHtml('Reviewed By', ['Name:', '______________________________', 'Position:', '______________________________', 'Signature:', '______________________________', 'Date:', '______________________________']);
        $html .= '</div>';
        $html .= '<div style="margin-top:18px;display:grid;grid-template-columns:1fr 1fr;gap:22px;font-size:11px;color:#334155;line-height:1.6;">';
        $html .= $this->buildApprovalBlockHtml('Approved By', ['Name:', '______________________________', 'Position:', '______________________________', 'Official Signature:', '______________________________', 'Official Stamp / Seal:', '______________________________', 'Approval Date:', '______________________________']);
        $html .= $this->buildApprovalBlockHtml('Printed By', ['System User:', $preparedBy, 'Role:', $role, 'Department:', $department, 'Printed On:', $printedOn, 'Timezone:', $timezone, 'Signature:', '______________________________']);
        $html .= '</div>';

        return $html;
    }

    private function buildApprovalBlockHtml(string $heading, array $fields): string
    {
        $html = '<div style="background:#ffffff;border:1px solid #cbd5e1;border-radius:12px;padding:14px;">';
        $html .= '<div style="font-weight:bold;color:#0f172a;margin-bottom:10px;">' . $heading . '</div>';
        foreach ($fields as $index => $value) {
            if ($index % 2 === 0) {
                $html .= '<div><strong>' . htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8') . '</strong> ' . htmlspecialchars((string) ($fields[$index + 1] ?? ''), ENT_QUOTES, 'UTF-8') . '</div>';
            }
        }
        $html .= '</div>';

        return $html;
    }

    private function buildQrCodeDataUri(string $payload): string
    {
        $builder = new Builder();
        $result = $builder->build(
            writer: new PngWriter(),
            data: $payload,
            errorCorrectionLevel: ErrorCorrectionLevel::High,
            size: 220,
            margin: 10,
        );

        return $result->getDataUri();
    }

    private function buildBarcodeDataUri(string $payload): string
    {
        $generator = new BarcodeGeneratorPNG();
        $barcode = $generator->getBarcode($payload, BarcodeGeneratorPNG::TYPE_CODE_128, 2, 60);

        return 'data:image/png;base64,' . base64_encode($barcode);
    }

    private function normalizeValue(mixed $value): string
    {
        if (is_array($value) || is_object($value)) {
            return json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }

        return (string) $value;
    }

    private function storeTempImage(string $dataUri): string
    {
        [$meta, $image] = explode(',', $dataUri, 2);
        $path = tempnam(sys_get_temp_dir(), 'report_export_') . '.png';
        file_put_contents($path, base64_decode($image));

        return $path;
    }
}
